# Generated by Django 3.0.6 on 2020-06-01 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('site_settings', '0002_auto_20200601_1739'),
    ]

    operations = [
        migrations.RenameField(
            model_name='socialmediasettings',
            old_name='twitter',
            new_name='instagram',
        ),
    ]
