# Generated by Django 3.0.6 on 2020-06-02 11:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0022_uploadedimage'),
        ('blog', '0003_blogauthorsorderable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogdetailpage',
            name='blog_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image'),
        ),
    ]
